import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "pixgen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${PoppinsFont.className} h-full antialiased`}>
      <body>
        <Navbar />

        <main className="max-w-7xl mx-auto">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
